apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins-limit-range
spec:
  limits:
  - default:
      cpu: 500m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 10m
      memory: 32Mi
    type: Container
